### ISSUE TITLE
Make booking notes character limit editable in settings

### ISSUE THREAD

**Issue by abramscheulderman** [craigrodway/classroombookings#26]
Hey Craig,

First of all: thank you for making this great tool. In addition to being a classroom booking tool, it is also great for managing available spaces during the COVID epidemic.

A small note from my side: Even in a very narrow browser window, The Workspace view button remains at 50% screen width and allows ample space for Names and notes, however by default a 15 character limit is hardcoded into bookings_model.php:
`$cell['body'] .= '<span title="'.$notes.'">'.character_limiter($notes, 15).'</span>';`

This limit seems rather low for the amount of horizontal space that is available in the 'room' field and that's without considering the ample vertical space for adding a second line of text. For our use case I simply increased the manual limit in bookings_model.php but am aware that this will need to be corrected after any future update to the code.

I think it would be helpful to expose the character limit value in the application settings, or at least increase the hardcoded limit as it currently seems unnecessarily low.

Thanks again for a great tool!

**Comment by craigrodway** [comment]
Hi, thanks for your comments! Happy to hear you've been able to make good use of it and I apologise for this late reply.

The 'Notes' value was limited to 15 characters due to the available space on the bookings grid. The cells get smaller the more columns there are, so it does need to be limited in some way to prevent extra-long Notes values from forcing the cells to be bigger than necessary.

I take this on board though, and agree it can be done better.

In the future,  I'm planning to add functionality where clicking on individual bookings will show more information in a small popup/overlay (and would include all the Notes); and/or the information displayed in the cells can be customised by a user-defined template or some form of settings.

**Comment by craigrodway** [comment]
HI abramscheulderman. From version 2.6, the booking Notes now appear in a separate panel when viewing the booking details, and aren't constrained by limits within the bookings grid itself.

Craig.
