### ISSUE TITLE
 installer not working 

### ISSUE THREAD

**Issue by Basondowah75** [craigrodway/classroombookings#48]
https://docs.classroombookings.com/assets/install-01.7e20b793.png

after providing everything to connect to the database noting happened it just refreshes the page

**Comment by craigrodway** [comment]
Hi, please follow all the [Troubeshooting steps](https://docs.classroombookings.com/version/2.6/open-source/troubleshooting.html#logging) in the documentation to find out where the problem is. However, at this stage, it's usually concerning the `local/sessions` folder - make sure it exists and has permissions.

**Comment by ankitiitj** [comment]
The bookings tab is giving an error HTTP ERROR 500.

Just to let you know, rest everything is working fine.

http://10.10.120.120/crbs/index.php/bookings 

![Uploading Screenshot 2023-01-17 at 6.23.13 PM.png…]()

**Comment by ankitiitj** [comment]
<img width="1440" alt="Screenshot 2023-01-17 at 6 24 42 PM" src="https://user-images.githubusercontent.com/69293547/212904263-1dd1ebcf-9880-4e2b-b855-54c476d90fd5.png">

**Comment by ankitiitj** [comment]
<img width="1440" alt="Screenshot 2023-01-17 at 6 23 13 PM" src="https://user-images.githubusercontent.com/69293547/212904366-edb40115-15cf-4736-907b-4502968e2f1d.png">

**Comment by craigrodway** [comment]
@ankitiitj, your report has nothing to do with this issue ("installer not working"); please do not comment on unrelated issues to report new problems.

But my response will be the same - follow the [troubleshooting steps](https://docs.classroombookings.com/version/2.6/open-source/troubleshooting.html#logging) to find the source of the problem.

If the problem is a genuine bug, please feel free to create a _new_ issue for it. 
If the problem is due to your setup, please correct it.
