### ISSUE TITLE
Multi Linguality

### ISSUE THREAD

**Issue by JoostTieleman** [craigrodway/classroombookings#53]
Hi

As happy user I miss Multi linguality.

I cannot code but I can offer you guys a translation to Dutch given a table provided.

Cheers,
Joost

**Comment by craigrodway** [comment]
Hello Joost, thanks for logging this issue.

Support for multiple languages is on the roadmap, but I don't have an estimate of when it will be launched at the moment.

**Comment by gabrielra6** [comment]
I would also very much like to have it translated into Portuguese. Take a look at POEDIT, I don't know if you already know it, but maybe it's a simpler way to implement multi-language support

**Comment by craigrodway** [comment]
Hi @gabrielra6, thanks for your comment and for mentioning POEDIT.

The main blocker is that all nearly all wording in classroombookings is currently embedded within the different code modules - rather than in a central place or in separate language files.

Extracting all the English wording into separate files is the first step to supporting multiple languages. Once that has been done, I can look into adding translations.
